---

- hosts: ansible-vm
  environment:
    JAVA_HOME: /usr/java/default
  roles:
    - role: ansible-java
      java_version: 8
      java_jdk_type: 'oracle'
      oracle_jdk_rpm_package: 'jdk-8u60-linux-x64.rpm'
      rpm_download_directory: '/vagrant/files'
      java_set_as_default: true

    - role: ansible-weblogic
      weblogic_jar_path: '/vagrant/files/fmw_12.2.1.2.0_infrastructure.jar'
      weblogic_quick_installation: false
      weblogic_installation_type: 'Fusion Middleware Infrastructure'
      weblogic_domain_name: 'oac_domain'

    - role: ansible-oac
      oac_jar_path: '/vagrant/files/fmw_12.2.1.2.0_oac.jar'
      oracle_db_address: '127.0.0.1'
      oracle_db_sid: 'orcl'
      oracle_db_password: 'password'
      oac_admin_server_listen_address: '127.0.0.1'
      oac_managed_server_listen_address: '127.0.0.1'

    - role: ansible-oag
      oag_prefix: "{{ oracle_base_dir }}/product/oag"
      oag_username: 'admin'
      oag_password: 'password'
      oag_hostname: '127.0.0.1'
      oag_port: '8090'
