---

- name: Install Oracle API Gateway
  shell: "/vagrant/files/OAG-11.1.2.4.0-linux-x64-installer.run --optionfile {{ oag.install_response_file }} > {{ oag.logs_dir }}/oag_installation_$(date +'%F').log 2>&1"

# - name: Copy NodeManager systemd script
#   template:
#     src: nodemanager.service.j2
#     dest: /etc/systemd/system/nodemanager-oag.service
#     mode: 0664
#   when: ansible_virtualization_type != 'docker'
#   become: yes
#   become_user: root

# - name: Copy Instance systemd script
#   template:
#     src: instance.service.j2
#     dest: /etc/systemd/system/instance-oag.service
#     mode: 0664
#   when: ansible_virtualization_type != 'docker'
#   become: yes
#   become_user: root

# - name: Enable Nodemanager service
#   service:
#     name: nodemanager-oag
#     enabled: yes
#   when: ansible_virtualization_type != 'docker'
#   become: yes
#   become_user: root

# - name: Enable Instance service
#   service:
#     name: instance-oag
#     enabled: yes
#   when: ansible_virtualization_type != 'docker'
#   become: yes
#   become_user: root

- set_fact:
    oag_already_installed: true
  when: oag_home.stat.exists
