---

- include: validate.yml
  tags:
    - always

- include: prepare.yml
  become: yes
  become_user: "{{ oracle.user }}"
  tags:
    - always
    
- include: install.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not oag_already_installed
  tags:
    - oag-install
    
- include: setpassword.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not oag_already_installed
  tags:
    - oag-install

- include: startnode.yml
  become: yes
  become_user: root
  when: not oag_already_installed
  tags:
    - oag-install

- include: configure.yml
  become: yes
  become_user: "{{ oracle.user }}"
  when: not oag_already_installed
  tags:
    - oag-install

- include: startinstance.yml
  become: yes
  become_user: root
  when: not oag_already_installed
  tags:
    - oag-install

